#!/usr/bin/env bash
# Configure server with: Nginx, custom 404, custom 301 redirect to google
# Add to HTTP header
REDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://youtube.com;\n\t}\n"
ADD404_NOTFOUND="error_page 404 /error_404.html;\n\\tlocation = /error_404.html {\n\t\t root /var/www/html;\n\t\tinternal;\n\t}\n"
PATTERN="#error_page 404 /404.html;"
ADD_HEADER="\\\tadd_header X-Served-By $HOSTNAME;"

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start

sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo "Hello World!" > /var/www/html/index.html

sudo sed -i "30i $REDIRECT" /etc/nginx/sites-available/default


echo "Ceci n'est pas une page" > /var/www/html/error_404.html
sudo sed -i "s@$PATTERN@$ADD404_NOTFOUND@" /etc/nginx/sites-available/default

sudo sed -i "27i $ADD_HEADER" /etc/nginx/sites-available/default

sudo service nginx restart
